# 为了试验，此处作为单独的 Workflow，在实际工作中可 Install -> Lint、Test -> Preview 串行检验
name: PULL REQUEST

# 执行 CI 的时机: 当 git push 到 feature-* 分支时
on:
  pull_request:
    branches: main

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if commit is from CI
        run: |
          if [[ "${{ github.event.head_commit.committer.username }}" == "github-actions[bot]" ]]; then
            echo "Commit is from CI, skipping the build..."
            exit 78
          else
            echo "Commit is not from CI, continuing with the build..."
          fi
      - name: see vars
        run: |
          echo '${{github.event.pull_request.head.ref}}'
          echo '${{github.event.pull_request.head.sha}}'
          echo '${{github.event.pull_request.head.repo.branches_url}}'
          echo '${{github.event.pull_request.base.ref}}'
          echo '${{github.event.pull_request.base.sha}}'
          echo '${{github.event.pull_request.base.repo.branches_url}}'
          echo '${{github.head_ref}}'
          echo '${{github.ref}}'
          echo '${{github.ref_name}}'
          echo '${{github.repository}}'
      - name: Checkout
        uses: actions/checkout/@v3
        with:
          fetch-depth: 1

      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          git fetch --unshallow
        env:
          GITHUB_TOKEN: ${{ github.token}}

      - name: see git1
        run: |
          git branch --show-current
      - name: see git2
        run: |
          git diff --name-only origin/main...HEAD
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16

      - name: Install LCAP
        run: |
          npm install -g lcap@0.3.4
          lcap config set platform https://defaulttenant.lcap.hadri.163yun.com
          lcap config set username admin
          lcap config set password Admin@123456
      - name: Install yarn
        run: npm install -g yarn@v1

      - name: Install Dep
        run: |
          yarn install --frozen-lockfile

      - name: Update Pull Request
        run: |
          git config --global core.quotepath false          
          git config --global gui.encoding utf-8            
          git config --global i18n.commit.encoding utf-8    
          git config --global i18n.logoutputencoding utf-8  
          export LESSCHARSET=utf-8
          yarn checkPR
        env:
          GITHUB_TOKEN: ${{ github.token}}
          PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
          BRANCH_NAME: ${{github.ref}}
          GITHUB_REPOSITORY: ${{github.repository}}
          ACTION_ID: ${{github.run_id}}

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Notify
        run: |
          yarn successPR
        env:
          GITHUB_TOKEN: ${{ github.token}}
          PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
          BRANCH_NAME: ${{github.ref}}
          GITHUB_REPOSITORY: ${{github.repository}}
          ACTION_ID: ${{github.run_id}}
